### ISSUE TITLE
安装到nova时启动服务报错（RedHat6.4 python2.6.6 openstack2013.1.2)

### ISSUE THREAD

**Issue by jerryw0** [yongluo2013/osf-openstack-training#2]
启动openstack-nova-cert服务时出错，仅有openstack-nova-api服务正常。

[ ] 1. - 016-08-16 09:34:47.228 5016 AUDIT nova.service [-] Starting cert node (version 2013.1-2.el6)
[ ] 2. - 2016-08-16 09:34:47.230 DEBUG nova.openstack.common.lockutils [req-14b575a6-c517-43c6-bbd1-4ec70b1c300a None None] Got semaphore "dbapi_backend" for method "**get_backend"... inner /usr/lib/python2.6/site-packages/nova/openstack/common/lockutils.py:186
[ ] 3. - 2016-08-16 09:34:47.680 5016 CRITICAL nova [-] 'module' object has no attribute 'create_connection'
[ ] 4. - 2016-08-16 09:34:47.680 5016 TRACE nova Traceback (most recent call last):
[ ] 5. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/bin/nova-cert", line 51, in <module>
[ ] 6. - 2016-08-16 09:34:47.680 5016 TRACE nova     service.wait()
[ ] 7. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/service.py", line 689, in wait
[ ] 8. - 2016-08-16 09:34:47.680 5016 TRACE nova     _launcher.wait()
[ ] 9. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/service.py", line 209, in wait
[ ] 10. - 2016-08-16 09:34:47.680 5016 TRACE nova     super(ServiceLauncher, self).wait()
[ ] 11. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/service.py", line 179, in wait
[ ] 12. - 2016-08-16 09:34:47.680 5016 TRACE nova     service.wait()
[ ] 13. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/eventlet/greenthread.py", line 166, in wait
[ ] 14. - 2016-08-16 09:34:47.680 5016 TRACE nova     return self._exit_event.wait()
[ ] 15. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/eventlet/event.py", line 116, in wait
[ ] 16. - 2016-08-16 09:34:47.680 5016 TRACE nova     return hubs.get_hub().switch()
[ ] 17. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/eventlet/hubs/hub.py", line 177, in switch
[ ] 18. - 2016-08-16 09:34:47.680 5016 TRACE nova     return self.greenlet.switch()
[ ] 19. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/eventlet/greenthread.py", line 192, in main
[ ] 20. - 2016-08-16 09:34:47.680 5016 TRACE nova     result = function(_args, *_kwargs)
[ ] 21. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/service.py", line 147, in run_server
[ ] 22. - 2016-08-16 09:34:47.680 5016 TRACE nova     server.start()
[ ] 23. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/service.py", line 442, in start
[ ] 24. - 2016-08-16 09:34:47.680 5016 TRACE nova     self.conn = rpc.create_connection(new=True)
[ ] 25. - 2016-08-16 09:34:47.680 5016 TRACE nova   File "/usr/lib/python2.6/site-packages/nova/openstack/common/rpc/__init**.py", line 96, in create_connection
[ ] 26. - 2016-08-16 09:34:47.680 5016 TRACE nova     return _get_impl().create_connection(CONF, new=new)
[ ] 27. - 2016-08-16 09:34:47.680 5016 TRACE nova AttributeError: 'module' object has no attribute 'create_connection'

是否因为Python版本导致出错，或者是没有安装依赖包导致。

**Comment by jerryw0** [comment]
上面问题已解决，
原因：
/etc/nova/nova.conf中rpc_backend配置错误
openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend qpid 
解决：
修改rpc_backend 值qpid为nova.rpc.impl_qpid
openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend nova.rpc.impl_qpid
