### ISSUE TITLE
glance初始化数据库出现错误。麻烦大神给看一下。

### ISSUE THREAD

**Issue by kgdmyd8778** [yongluo2013/osf-openstack-training#5]
[root@wcg ~]# openstack-db --init --service glance --password openstack
Please enter the password for the 'root' MySQL user: 
Verified connectivity to MySQL.
Creating 'glance' database.
Updating 'glance' database password in /etc/glance/glance-registry.conf /etc/glance/glance-api.conf
Initializing the glance database, please wait...
Traceback (most recent call last):
  File "/usr/bin/glance-manage", line 6, in <module>
    from glance.cmd.manage import main
  File "/usr/lib/python2.6/site-packages/glance/cmd/manage.py", line 45, in <module>
    from glance.db import migration as db_migration
  File "/usr/lib/python2.6/site-packages/glance/db/__init__.py", line 21, in <module>
    from glance.common import crypt
  File "/usr/lib/python2.6/site-packages/glance/common/crypt.py", line 24, in <module>
    from Crypto import Random
ImportError: cannot import name Random
Error updating the database. Please see /var/log/glance/ logs for details.

**Comment by jie-d-cheng** [comment]
解决没有啊，我也遇到这个问题了。

**Comment by jie-d-cheng** [comment]
https://ask.openstack.org/en/question/28335/you-should-rebuild-using-libgmp-5-to-avoid-timing-attack-vulnerability-_warnnot-using-mpz_powm_sec-you-should-rebuild-using-libgmp-5-to-avoid-timing/
